name: 🐛 Bug Report
description: Report a bug or issue
title: '[Bug]: '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: When I try to...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - iOS
        - Android
        - Both
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of VoiceFlow are you running?
      placeholder: v2.1.1
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: API Provider (if relevant)
      options:
        - Not applicable
        - OpenAI
        - Anthropic
        - Google
        - Multiple providers

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: This is not an API provider issue
          required: false
