name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'needs-discussion']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please note that VoiceFlow is privacy-first,
        so features requiring servers or data collection are unlikely to be accepted.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I often need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Critical for my use case

  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy Considerations
      options:
        - label: This feature can work entirely offline
        - label: This feature requires no additional permissions
        - label: This feature stores no additional data

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
